import {
    createSlice,
    createEntityAdapter,
    createAsyncThunk,
} from "@reduxjs/toolkit";
import postService from "../../services/postService";

// Use Entity Adapter to normalize data
const postsAdapter = createEntityAdapter({
    selectId: (post) => post.id,
    sortComparer: (a, b) => {
        const dateA = a.createdAt || "";
        const dateB = b.createdAt || "";
        return dateB.localeCompare(dateA);
    },
});

export const fetchPosts = createAsyncThunk(
    "posts/fetchPosts",
    async ({ page, size }, { rejectWithValue }) => {
        try {
            const response = await postService.getFeedPosts(page, size);
            return response;
        } catch (error) {
            return rejectWithValue(error.apiResponse || error.message);
        }
    },
);

export const toggleLike = createAsyncThunk(
    "posts/toggleLike",
    async (postId, { rejectWithValue }) => {
        try {
            const response = await postService.toggleLikePost(postId);
            return { postId, ...response }; // response should have isLiked, likeCount
        } catch (error) {
            return rejectWithValue({ postId, error: error.apiResponse || error.message });
        }
    },
);

const postSlice = createSlice({
    name: "posts",
    initialState: postsAdapter.getInitialState({
        status: "idle",
        error: null,
        hasMore: true,
        page: 0,
    }),
    reducers: {
        // UI Optimization: Like post immediately (Optimistic Update)
        toggleLikePost: (state, action) => {
            const { postId, userId } = action.payload;
            const post = state.entities[postId];
            if (post) {
                const wasLiked = post.isLiked;
                post.isLiked = !wasLiked;
                post.likeCount += wasLiked ? -1 : 1;
            }
        },
        // Mock data for UI testing
        setMockPosts: (state, action) => {
            postsAdapter.setAll(state, action.payload);
        },
        addMockPosts: (state, action) => {
            postsAdapter.upsertMany(state, action.payload);
        },
    },
    extraReducers: (builder) => {
        builder
            .addCase(fetchPosts.pending, (state) => {
                state.status = "loading";
            })
            .addCase(fetchPosts.fulfilled, (state, action) => {
                state.status = "succeeded";
                postsAdapter.upsertMany(state, action.payload);
                state.hasMore = action.payload.length > 0;
            })
            .addCase(fetchPosts.rejected, (state, action) => {
                state.status = "failed";
                state.error = action.payload;
            })
            .addCase(toggleLike.pending, (state, action) => {
                const postId = action.meta.arg;
                const post = state.entities[postId];
                if (post) {
                    // Optimistic update
                    const wasLiked = post.isLiked;
                    post.isLiked = !wasLiked;
                    post.likeCount += wasLiked ? -1 : 1;
                }
            })
            .addCase(toggleLike.fulfilled, (state, action) => {
                const { postId, isLiked, likeCount } = action.payload;
                const post = state.entities[postId];
                if (post) {
                    // Sync with real data from server
                    post.isLiked = isLiked;
                    post.likeCount = likeCount;
                }
            })
            .addCase(toggleLike.rejected, (state, action) => {
                const { postId } = action.payload;
                const post = state.entities[postId];
                if (post) {
                    // Rollback on error
                    const wasLiked = post.isLiked;
                    post.isLiked = !wasLiked;
                    post.likeCount += wasLiked ? -1 : 1;
                }
            });
    },
});

export const { toggleLikePost, setMockPosts, addMockPosts } = postSlice.actions;

// Selectors automatically generated by the Adapter
export const {
    selectAll: selectAllPosts,
    selectById: selectPostById,
    selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);

export default postSlice.reducer;
