import { createSlice, createEntityAdapter, createAsyncThunk } from '@reduxjs/toolkit';

// Use Entity Adapter to normalize data
const postsAdapter = createEntityAdapter({
  selectId: (post) => post.id,
  sortComparer: (a, b) => {
    const dateA = a.createdAt || '';
    const dateB = b.createdAt || '';
    return dateB.localeCompare(dateA);
  },
});

export const fetchPosts = createAsyncThunk(
  'posts/fetchPosts',
  async ({ page, size }, { rejectWithValue }) => {
    try {
      // Temporary use dummy data, will call API from Spring Boot later
      // const response = await postService.getAllPosts(page, size);
      // return response.data;
      return []; 
    } catch (error) {
      return rejectWithValue(error.response.data);
    }
  }
);

const postSlice = createSlice({
  name: 'posts',
  initialState: postsAdapter.getInitialState({
    status: 'idle',
    error: null,
    hasMore: true,
    page: 0,
  }),
  reducers: {
    // UI Optimization: Like post immediately (Optimistic Update)
    toggleLikePost: (state, action) => {
      const { postId, userId } = action.payload;
      const post = state.entities[postId];
      if (post && post.likedBy) {
        const index = post.likedBy.findIndex(u => u.id === userId);
        if (index === -1) {
          // Mock: Add ID to array (in reality it will be a full user object from API)
          post.likedBy.push({ id: userId });
          post.likeCount += 1;
        } else {
          post.likedBy.splice(index, 1);
          post.likeCount -= 1;
        }
      }
    },
    // Mock data for UI testing
    setMockPosts: (state, action) => {
      postsAdapter.setAll(state, action.payload);
    },
    addMockPosts: (state, action) => {
      postsAdapter.upsertMany(state, action.payload);
    }
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchPosts.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = 'succeeded';
        postsAdapter.upsertMany(state, action.payload);
        state.hasMore = action.payload.length > 0;
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.payload;
      });
  },
});

export const { toggleLikePost, setMockPosts, addMockPosts } = postSlice.actions;

// Selectors automatically generated by the Adapter
export const {
  selectAll: selectAllPosts,
  selectById: selectPostById,
  selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);

export default postSlice.reducer;
