import {
    createSlice,
    createEntityAdapter,
    createAsyncThunk,
} from "@reduxjs/toolkit";
import postService from "../../services/postService";

// Use Entity Adapter to normalize data
const postsAdapter = createEntityAdapter({
    selectId: (post) => post.id,
    sortComparer: (a, b) => {
        const dateA = a.createdAt || "";
        const dateB = b.createdAt || "";
        return dateB.localeCompare(dateA);
    },
});

export const fetchPosts = createAsyncThunk(
    "posts/fetchPosts",
    async ({ cursor, size }, { rejectWithValue }) => {
        try {
            const response = await postService.getFeedPosts(cursor, size);
            return response; // Should be { posts: [], nextCursor: string, hasMore: boolean }
        } catch (error) {
            return rejectWithValue(error.apiResponse || error.message);
        }
    },
);

export const toggleLike = createAsyncThunk(
    "posts/toggleLike",
    async (postId, { rejectWithValue }) => {
        try {
            const response = await postService.likePost(postId);
            return { postId, ...response }; // response: { isLiked, likeCount }
        } catch (error) {
            return rejectWithValue({ postId, error: error.apiResponse || error.message });
        }
    },
);

const postSlice = createSlice({
    name: "posts",
    initialState: postsAdapter.getInitialState({
        status: "idle",
        error: null,
        hasMore: true,
        nextCursor: null,
    }),
    reducers: {
        resetPosts: (state) => {
            postsAdapter.removeAll(state);
            state.status = "idle";
            state.nextCursor = null;
            state.hasMore = true;
        },
        updatePostInStore: (state, action) => {
            const { id, changes } = action.payload;
            if (changes.archived === true) {
                postsAdapter.removeOne(state, id);
            } else {
                postsAdapter.updateOne(state, {
                    id: id,
                    changes: changes,
                });
            }
        },
    },
    extraReducers: (builder) => {
        builder
            .addCase(fetchPosts.pending, (state) => {
                state.status = "loading";
            })
            .addCase(fetchPosts.fulfilled, (state, action) => {
                state.status = "succeeded";
                // Action payload is FeedResponse: { posts[], nextCursor, hasMore }
                const { posts, nextCursor, hasMore } = action.payload;
                postsAdapter.upsertMany(state, posts);
                state.nextCursor = nextCursor;
                state.hasMore = hasMore;
            })
            .addCase(fetchPosts.rejected, (state, action) => {
                state.status = "failed";
                state.error = action.payload;
            })
            .addCase(toggleLike.pending, (state, action) => {
                const postId = action.meta.arg;
                const post = state.entities[postId];
                if (post) {
                    // Optimistic update
                    const wasLiked = post.isLiked;
                    post.isLiked = !wasLiked;
                    post.likeCount += wasLiked ? -1 : 1;
                }
            })
            .addCase(toggleLike.fulfilled, (state, action) => {
                const { postId, isLiked, likeCount } = action.payload;
                const post = state.entities[postId];
                if (post) {
                    // Sync with real data from server
                    post.isLiked = isLiked;
                    post.likeCount = likeCount;
                }
            })
            .addCase(toggleLike.rejected, (state, action) => {
                const { postId } = action.payload;
                const post = state.entities[postId];
                if (post) {
                    // Rollback on error
                    const wasLiked = post.isLiked;
                    post.isLiked = !wasLiked;
                    post.likeCount += wasLiked ? -1 : 1;
                }
            });
    },
});

export const { resetPosts, updatePostInStore } = postSlice.actions;

// Selectors automatically generated by the Adapter
export const {
    selectAll: selectAllPosts,
    selectById: selectPostById,
    selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);

export default postSlice.reducer;
